#!/bin/bash
#	written by walkerd1217@gmail.com
#	The purpose of this script is to update/upgrade the system & ease the 
#	installation/configuration of clamav and rkhunter.

echo -e "********************************************************************************"
echo -e "* This script is not intended to handle passowrds                              *"
echo -e "* any password prompts come from the system                                    *"
echo -e "* as an alternative to running this script, the commands may be run manually.  *"
echo -e "* to view the contents of this script, open it in any text editor.             *"
echo -e "* press 'ctrl+c' to kill the running process at any time.                      *"
echo -e "********************************************************************************"

# update and upgrade system
echo -e "**************************"
echo -e "* Updating and upgrading *"
echo -e "**************************"
sudo apt-get update && sudo apt-get dist-upgrade -y

# install clamav
echo -e "*********************************"
echo -e "* Installing 'clamav' antivirus *"
echo -e "*********************************"
sudo apt-get install clamav -y

# install rkhunter
echo -e "*****************************************"
echo -e "* Installing 'rkhunter' root-kit hunter *"
echo -e "*****************************************"
sudo apt-get install rkhunter -y

# configure rkhunter
echo -e "*******************************"
echo -e "* configuring 'rkhunter.conf' *"
echo -e "*******************************"

#quick permission change to allow easy edits
#this should be revised for security purposes as 777 is excessive and +s may be unnecessary
sudo chmod 777 /etc/rkhunter.conf
sudo chmod +s /etc/rkhunter.conf

# whitelisting /usr/bin/egrep so that rkhunter will run
while read a; do
	echo ${a//'SCRIPTWHITELIST=/usr/bin/egrep'/'#SCRIPTWHITELIST=/usr/bin/egrep'}
done < /etc/rkhunter.conf > /etc/rkhunter.conf.t
sudo mv /etc/rkhunter.conf{.t,}

# whitelisting /usr/bin/fgrep so that rkhunter will run
while read a; do
        echo ${a//'SCRIPTWHITELIST=/usr/bin/fgrep'/'#SCRIPTWHITELIST=/usr/bin/fgrep'}
done < /etc/rkhunter.conf > /etc/rkhunter.conf.t
sudo mv /etc/rkhunter.conf{.t,}

#changing the file permissions back to where they should be
sudo chmod 544 /etc/rkhunter.conf


# update rkhunter & run scan
echo -e "********************************************************"
echo -e "* Updating 'rkhunter to use revised configuration file *"
echo -e "********************************************************"

sudo rkhunter -C
sudo rkhunter --propupd

echo -e "********************************************************"
echo -e "* Running preliminary 'rkhunter scan' please wait....  *"
echo -e "********************************************************"

sudo rkhunter -c -sk

echo -e "******************************************************************"
echo -e "* ...Finished.  Enter 'sudo rkhunter -c -sk' to run future scans *"
echo -e "******************************************************************"

echo -e "*********************************************"
echo -e "* You are now ready to visit candy mountain *"
echo -e "*********************************************"
