#!/bin/bash
#	written by walker.derek@protonmail.com
#	The purpose of this script is to update/upgrade the system & automate the 
#	installation/configuration of clamav and rkhunter on linux mint 20.
#	Enabling host based firewall (ufw) added 10/23/2020
#	Updated email address, & added suggestion for pause feature before the remainder of th script runs.

echo -e "********************************************************************************"
echo -e "* This script is not intended to handle passowrds                              *"
echo -e "* any password prompts come from the system                                    *"
echo -e "* as an alternative to running this script, the commands may be run manually.  *"
echo -e "* to view the contents of this script, open it in any text editor.             *"
echo -e "* press 'ctrl+c' to kill the running process at any time.                      *"
echo -e "********************************************************************************"

# <--Add pause for "press 'ctrl+c' to kill script, any other key to continue."
# <--Add code for configuring dns servers with 1.1.1.1 & 1.0.0.1
# <--Add option for fixing system time for dual boot situations
# <--Add option to customize the grub boot menu 

# update and upgrade system
echo -e "**************************"
echo -e "* Updating and upgrading *"
echo -e "**************************"
sudo apt-get update && sudo apt-get dist-upgrade -y

# enable host based firewall (ufw)
echo -e "********************************"
echo -e "* Enabling host based firewall *"
echo -e "********************************"
sudo ufw enable

# install clamav
echo -e "*********************************"
echo -e "* Installing 'clamav' antivirus *"
echo -e "*********************************"
sudo apt-get install clamav -y

# install rkhunter
echo -e "*****************************************"
echo -e "* Installing 'rkhunter' root-kit hunter *"
echo -e "*****************************************"
sudo apt-get install rkhunter -y

##################################################################################################
# no longer needed as issues requiring this change have been resolved within os updates
##################################################################################################
# configure rkhunter
#echo -e "*******************************"
#echo -e "* configuring 'rkhunter.conf' *"
#echo -e "*******************************"

#quick permission change to allow easy edits
#this should be revised for security purposes as 777 is excessive and +s may be unnecessary
#sudo chmod 777 /etc/rkhunter.conf
#sudo chmod +s /etc/rkhunter.conf

# un-whitelisting /usr/bin/egrep so that rkhunter will run
#while read a; do
#	echo ${a//'SCRIPTWHITELIST=/usr/bin/egrep'/'#SCRIPTWHITELIST=/usr/bin/egrep'}
#done < /etc/rkhunter.conf > /etc/rkhunter.conf.t
#sudo mv /etc/rkhunter.conf{.t,}

# un-whitelisting /usr/bin/fgrep so that rkhunter will run
#while read a; do
#        echo ${a//'SCRIPTWHITELIST=/usr/bin/fgrep'/'#SCRIPTWHITELIST=/usr/bin/fgrep'}
#done < /etc/rkhunter.conf > /etc/rkhunter.conf.t
#sudo mv /etc/rkhunter.conf{.t,}

#changing the file permissions back to where they should be
#sudo chmod 544 /etc/rkhunter.conf

# update rkhunter & run scan
#echo -e "********************************************************"
#echo -e "* Updating 'rkhunter to use revised configuration file *"
#echo -e "********************************************************"
#sudo rkhunter -C
##########################################################################################

sudo rkhunter --propupd

echo -e "********************************************************"
echo -e "* Running preliminary 'rkhunter scan' please wait....  *"
echo -e "********************************************************"

sudo rkhunter -c -sk

echo -e "******************************************************************"
echo -e "* ...Finished.  Enter 'sudo rkhunter -c -sk' to run future scans *"
echo -e "******************************************************************"

echo -e "*********************************************"
echo -e "* You are now ready to visit candy mountain *"
echo -e "*********************************************"
